### ISSUE TITLE
Yay/ARU Install error: install command is not scriptable

### ISSUE THREAD

**Issue by tmilner** [hyprwm/hyprlock#220]
When attempting to install hyprlock-git package from the ARU with yay I get the following error:
 
```
CMake Error at build/cmake_install.cmake:64 (install):
  install command is not scriptable


==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: hyprlock-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
hyprlock-git - exit status 4
```

I saw that there was a similar error with Nix fixed here, https://github.com/hyprwm/hyprlock/commit/f237dead6cf7c79b713168fb1053758c771a1dfe

**Comment by vaxerski** [comment]
likely a problem with the package. Builds just fine manually for me.

**Comment by alerque** [comment]
The release version of v0.3.0 is broken the same way. I see the VCS package in the AUR is applying a patch labeled for Nix that probably relates to this, but that is a bit ridiculous. The CMakeLists.txt file should just be fixed.

**Comment by vaxerski** [comment]
the CMakeLists is not broken, though. It works on my end.

The reason it's there is to not overwrite the pam entry with the default if it already exists. See #209

If you have a different way of achieving the same, that is more compatible, be my guest.

**Comment by alerque** [comment]
"Works for me" does not make it correct.

I suspect the issue is you are inadvertently testing the host system root instead of (in the case of nearly every distro packaging system out there) the DEST directory where files to be packaged are collected. I don't know my way around CMake, but surely it has a variant of an `install()` function that handles this kind of use automatically, you shouldn't have to hand check a file like that. In the case of distro packages it will handle creation or update of system files automatically, the job of CMake is just to "install" stuff to a blank directory structure.

**Comment by vaxerski** [comment]
I think not throwing this into a script should work too... but that's a method I found on the cmake mailing list. Gimme sec.

**Comment by vaxerski** [comment]
yeaaah that doesn't work. I think this could be better addressed when #205 lands, as we can overwrite the hyprlock pam file and just ask people to make a custom file they can set in the config.

I'll reopen this

**Comment by vaxerski** [comment]
should be done with d9a6229434fba475ea42b634ee2f03919236798d

**Comment by alerque** [comment]
Okay thanks.

I've backported that patch and applied to v0.3.0, and also marked `/etc/pam.d/hyprlock` for backup (so that the package can update it in the future but any user applied edits to the file will get preserved and the user prompted to merge changes from the new package supplied version) and updated the Arch Linux package repos.

**Comment by vaxerski** [comment]
thanks for the maintenance work :)
