### ISSUE TITLE
[REQ] Add custom shape

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/hyprlock#253]
Some users (aka me, nobody cares) may want to fill a custom rectangle as background of labels, input, whatever, to better distinguish them from the all other stuff. At the moment this can be done with an image (like picture below), but this has disadvantages:
- You need a .png picture of solid color, want to change it - go to gimp, ugh
- Picture must be with specific ratio, same as above

![2024-04-01T12:00:06,417336041+04:00](https://github.com/hyprwm/hyprlock/assets/142721811/6d6dc4ad-3bda-48b5-9e76-6473f9f5bd6f)

It would be easier, if there will be a widget, that just fill rectangle of custom shape with specified color, that also has border, shadow and all eye candy stuff. Also it must lay behind other widgets - images, labels etc. Basically something like this:

```
shape (or a rectangle, box, doesn't matter how it called) {
    monitor =
    color = rgba(14881337) # background color
    size = 228, 228 # x, y
    rounding = 69 # negative values mean circle
    border_size = 1
    border_color = rgb(696969)
    rotate = 0 # degrees, counter-clockwise

    # All shadow stuff ...

    position = 0, 0
    halign = center
    valign = center
}
```

**Comment by bvr-yr** [comment]
I've been thinking of it, but for another purpose
I was looking for a method to use cava, and one I like the most is just cropping a rect in backround with 0 alpha and spawning cava sdl window before hyprlock. 

Kinda like this

![173639-output- eDP-1](https://github.com/hyprwm/hyprlock/assets/130279855/b3d2981e-d837-48f6-9ee0-e6e0f7a594df)

this doesn't work with blur tho (works but sucks), but I can add rounding and shadows (inkscape)

I know how to implement this easily, but without rounding and shadows
@vaxerski is there a convenient way to achieve above?

If so, just make it like `xray` option and draw nothing instead of shape. Could be also used for different purpose, mpv for example

**Comment by vaxerski** [comment]
kinda stupid imo

**Comment by bvr-yr** [comment]
what exactly? empty rect or a whole widget?

**Comment by Ligthiago** [comment]
Not sure why such a interface primitive, which can be used in different ways, is stupid. 
Implementing it with an image is even worse, instead of just specifying shape with a few lines in the config, you have to handcraft image and store it. Or there are better solution to achieve this?
