### ISSUE TITLE
[Feature Request] render password as text symbol

### ISSUE THREAD

**Issue by namaek2** [hyprwm/hyprlock#316]
![image](https://github.com/hyprwm/hyprlock/assets/34965961/1cf68697-69fb-4cb7-9a2f-da3bbc3ebdf6)
- image is from : https://github.com/stepanzubkov/where-is-my-sddm-theme/commits?author=stepanzubkov

I want to render password dots as asterisk like this image.

I looked up code little bit and find out dots are rendered by CRenderer::renderRect function. Is there any plan to render password as text?

**Comment by vaxerski** [comment]
MRs welcome

**Comment by HarshNarayanJha** [comment]
Hey, I would like to work on this. I am quite new to C++, and digging down, here's what I found

The exact line which is drawing the dots
https://github.com/hyprwm/hyprlock/blob/eb63207ef051c62fa2ab010b3f89da263a397329/src/renderer/widgets/PasswordInputField.cpp#L271

So I might try to use a `CLabel` to draw the * (or whatever is set in config). Right?

**Comment by PaideiaDilemma** [comment]
Hey @HarshNarayanJha 

FYI, I implemented this. Just wanted to wait for #508 until i create the MR.
You are welcome to look at my current implementation here: https://github.com/PaideiaDilemma/hyprlock/commit/057b6b8c17bb4f98ed9b5375d925491d41b584ab

Let me know what you think the config option should be named like.

**Comment by PaideiaDilemma** [comment]
> Didn't see that one! 😓

Yeah sorry, I could have posted that i am going to implement that.

> What I think (if I am not wrong), say textAsset did get allocate, in this case dots must be drawn as fallback option

Yeah so this is intended. We set `forceReload` to true as long as the asset is not ready yet. So we relay on the asyncResourceGatherer to successfully render that asset at some point. Otherwise we will busy render forever.
That works the same as the background widget for example.
I am not 100% happy with the break in the loop though
