### ISSUE TITLE
Hyprlock unlocks when executed second time

### ISSUE THREAD

**Issue by ejb-11** [hyprwm/hyprlock#382]
When Hyprlock is already running, when the program is launched a second time (e.g. by using a Hyprland keybinding) the current instance unlocks. Both processes continue to exist but neither of them keep the screen locked. I discovered this when I had a typo in my Hyprland config (I had `pid hyprlock || hyprlock` instead of `pidof hyprlock || hyprlock`).

This is rather strange behaviour. I think the expected behaviour is for the second instance to simply go into a dormant state or quit, with the running one left alone.

Mitigating this problem on the user-side is easy; simply check if an instance is already running before launching Hyprlock, as in the second example above (which was in the example Hypridle config on the Hyprland Wiki).

**Comment by PaideiaDilemma** [comment]
Thant should not happen. However I cannot reproduce the problem with `sleep 10 && hyprlock` nor using hypridle to launch hyprlock.

Are you on hyprland git? What are the logs of the two instances, when it happens?

**Comment by ejb-11** [comment]
@lolwat97 Yes, I am running NixOS.

**Comment by PaideiaDilemma** [comment]
Yeah thats probably a hyprland issue that has already been fixed.

**Comment by ejb-11** [comment]
> Yeah thats probably a hyprland issue that has already been fixed.

I think it is related to #351.

**Comment by PaideiaDilemma** [comment]
Probably. Hard to know, when used versions are unknown. Please post your hyprland version (`hyprctl version`).
Have you updated yet and checked if it is fixed?

**Comment by PaideiaDilemma** [comment]
> Hyprlock somehow "unlocking" itself if the second instance of hyprlock is launched

Kind of but not really. Even though https://github.com/hyprwm/hyprlock/pull/376 was named that way, calling `ext_session_lock_v1_unlock_and_destroy(m_sLockState.lock)` in a second instance of hyprlock should never unlock the initial one. Otherwise every application could just unlock the session lock. You need the correct session lock object that locked the session in the first place. The current implementation just exiting is also not really the correct way of handling the `finished` event as a session lock client.

>  Upon receiving this event, the client should make either the destroy request or the unlock_and_destroy request, depending on whether or not the locked event was received on this object.

See [finished](https://wayland.app/protocols/ext-session-lock-v1#ext_session_lock_v1:event:finished).

**Comment by ejb-11** [comment]
I have updated my `flake.lock` to the latest version of Nixpkgs and the problem no longer persists because the keybind no longer works on the lock screen (it is eaten by the password input prompt as a regular keypress, ignoring the super key). This is the intended behaviour since it is not a `bindl` keybind. Testing it as a `bindl` keybind also no longer produces this error.

Hopefully that's the issue sorted. Cheers!
