### ISSUE TITLE
[ERR] Resource background invalid (out of memory)

### ISSUE THREAD

**Issue by Aligehri** [hyprwm/hyprlock#388]
I have two monitors and i was able to use just one wallpaper, but now anyone. I tried resizing and renaming with .png. Nothing works. My wallpapers are 400kb and 900kb. Any other solution?

**Comment by vaxerski** [comment]
"out of memory" is a blanket error for failing to load an image. Try a different image

**Comment by bktech2021** [comment]
I got the same error with config ```
image {
    monitor = 
    path = ~/.face
    size = 100
    border_color = $accent

    position = 0, 75
    halign = center
    valign = center
}
```
I tried webp, png and jpeg. I'm going to crop image. I'll write if that works.

**Comment by bktech2021** [comment]
Resized and formatted to 800x800 PNG has worked. Previous image was 3000x4000 JPEG. Also don't use `~` as home directory, write full name of the file, like `/home/user/.face`. I don't know why but it can't find it. If the problem is solved, close the issue. If not feel free to write down.

**Comment by Aligehri** [comment]
That was not the solution i was looking for. I write a script that changes to the 5 and 10 workspace and then hyprlock. With that I have the wallpaper I want and they fit as I want . 

#!/bin/bash
hyprctl dispatch workspace 5
hyprctl dispatch workspace 10
hyprlock

those workspaces are always empty.

**Comment by Rolv-Apneseth** [comment]
> That was not the solution i was looking for. I write a script that changes to the 5 and 10 workspace and then hyprlock. With that I have the wallpaper I want and they fit as I want .
> 
> #!/bin/bash hyprctl dispatch workspace 5 hyprctl dispatch workspace 10 hyprlock
> 
> those workspaces are always empty.

Thanks, exactly what I was looking for since none of the images are working (they're all random resolutions, I assume that's it). I have the option where triggering the same workspace that you're on goes back to the previous one, so I use `hyprctl dispatch workspace 10 && hyprlock &&  hyprctl dispatch workspace 10` which works nicely

**Comment by jjramsey** [comment]
@Aligehri I think you closed this bug too early. While I'm glad you found a workaround, there's no good reason that hyprlock should fail to show an image that can be readily viewed on a modern monitor -- especially since hyprland's specialty is supposed to be eye candy.

**Comment by jjramsey** [comment]
> "out of memory" is a blanket error for failing to load an image. Try a different image

@vaxerski  Judging from this SO post, it comes from Cairo getting confused, for example, by trying to read a JPG as a PNG: https://stackoverflow.com/questions/77384048/cairo-image-surface-create-from-png-returns-out-of-memory-but-i-have-enough

I'm not saying that's exactly what's happening here' I'm sure it's more complicated than that. However, I did notice that when I converted my background from JPG to PNG, hyprlock behaved itself and showed the background image.

My best guess is that something is going wrong in how `JPEG::createSurfaceFromJPEG()` is being handled, but I don't really know.

**Comment by jjramsey** [comment]
@Aligehri Just as a matter of principle, you shouldn't close a bug just because you found a workaround.

FWIW, I found this bug report because I encountered the same error message, though in my case it was because I was using a version of hyprlock that only had PNG support. (At the time that I write this, the Arch Linux package for the latest release of hyprlock is still in the Extra-Testing repo. Hopefully, this latest release will fix the problem.)
