### ISSUE TITLE
Feature request: Immediately black out the screen when `--immediate` flag is used

### ISSUE THREAD

**Issue by Hubro** [hyprwm/hyprlock#389]
When locking the screen before the PC suspends, it's important that this happens *fast*. It's really disconcerting when the monitor is visible for a couple of seconds after waking the PC before the lock screen fades in, and it could conceivably be a security issue in some cases.

I think it would be nice if the `--immediate` flag caused hyprlock to black out the screen as soon as possible, before doing any other non-critical setup like loading images.

This would ensure that when the machine resumes, there's only a black screen while hyprlock finishes its setup and can fade in the nice lock background image.

For backwards compatibility this could also be a new flag with the name `--sleep`, `--blackout` etc.

**Comment by mathewp88** [comment]
+1 for this.

I did some testing, and it seems that loading the background image is what causes this issue. As a temporary workaround, I've set a background color instead of an image, this makes the lock screen appear immediately. I think adding a reload option for the background image would fix this.

**Comment by PaideiaDilemma** [comment]
I think we could do something like rendering the configured color when the background is not available yet.

Although even my shitty laptop renders a 8mb image very fast and I have no delay at all. I also cannot relate to the suspend thing, because I have never experienced hyprlock still showing the workspace, when the device wakes again.

**Comment by mathewp88** [comment]
Yeah, that should fix this.

I have no idea why it takes so long to render the image, there's a delay with even small images ( under 200kb). At first I thought it was something to do with nvidia, but it's the same with an igpu.

**Comment by PaideiaDilemma** [comment]
Any thoughts about these decisions?
- Should this also be a config option or just a flag?
- Should fade_in also be disabled when this is used? (In my current impl it still fades. Also works but maybe you want no fade in that case)
- `--blackout` is ok as a name, but you can configure the color. Any naming ideas would be a better fit?

**Comment by mathewp88** [comment]
- I think it should be a config option, but that's just my preference and I don't really think there's any issue with it being a flag either.
- I think it should just respect whatever is present in the config and not overdrive the fade_in option.
- `--blackout` seems ok, but perhaps, `--unloaded` or `--no_load` is better suited, as hyprlock essentially starts without anything rendered in.

**Comment by PaideiaDilemma** [comment]
Please check out the PR if you have time and tell me what you think :)

**Comment by PaideiaDilemma** [comment]
> For the purposes of covering the screen as fast as possible, it would be better if the fade animation was disabled as well.

True, but i kinda like it more just having it independent of the fade-in. I guess we could just add a `--no-fade-in` cli flag as well and then you have to fastest way actually mute your screen with `--immediate --immediate-render --no-fade-in`.

But in your case, I guess it starts to fade in the solid color and then switches to fading in the actual background??

For `path=screenshot` the background is always fast enough to not show a solid color on my system, so for me, using `general:immediate_render` also just improves the startup time, which is nice.
But it is not a default, because rendering the solid color can definitely happen and that can look a bit yanky.
