### ISSUE TITLE
components positioning not working properly after lates update

### ISSUE THREAD

**Issue by firashacker** [hyprwm/hyprlock#425]
after latest update my clock position changed it was sat to -100,-40
and this heppend

![lockscreen](https://github.com/user-attachments/assets/d9e06610-35f3-4787-9695-638c3e76bd66)

i changed the -40 to 40 to get it back where it was

**Comment by vaxerski** [comment]
@PaideiaDilemma

**Comment by PaideiaDilemma** [comment]
Bisected to 84c6282d6a1f6ab4ecff791e0b957d354f894121 (before v0.3.0)

Only affects `valign=bottom`.

This line is the culprit: [posFromHVAlign valign bottom](https://github.com/hyprwm/hyprlock/blob/9514925a7c4c11028b6e3aae548b9c6859849462/src/renderer/widgets/IWidget.cpp#L44C9-L44C28)

Before the commit it was `pos.y += size.y;`, which offset the label from the bottom by it's size.
After the commit it s `pos.y += 0 - rot.y;` which makes it the same as `valign=none` if no rotation is used.

Mentioned in the PR here: https://github.com/hyprwm/hyprlock/pull/234#discussion_r1543429814 and also there was https://github.com/hyprwm/hyprlock/pull/235

I did not realize this was changed, because I don't use `valign=bottom`

**Comment by PaideiaDilemma** [comment]
I would leave it like it is now, since a lot of people already adapted probably (since v0.3.0 already has this behavior).
I think it is more intuitive, since `position=0,0` and `valign=bottom` places it properly at the bottom.

**Comment by firashacker** [comment]
so i should keep my config like it is now after modification, and future updates won't break it again :) ?

**Comment by PaideiaDilemma** [comment]
It is definitely not planed that we break it again xD

Just if we decide to revert to the previous behavior.
Any opinions @vaxerski ?

**Comment by vaxerski** [comment]
leave it
